name: my_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pywr
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
  - matplotlib=3.8
  - networkx=3.3
  - pytables=3.9.2
  - xlrd=2.0.1
  - cython=3.0.10
  - packaging=24.1
  - pytest=8.2.2
  - glpk=5.0
  - jupyter
